// MaskCipher — FNV-1a seeded LCG keystream (NR constants), per-byte XOR.
//
// Codec family: fnv_lcg. Salt length is 24 bytes and keystream length is 29.
// Shrouded payloads live in `../charts/shrouded_payload.dart`; `revealBytes`
// consumes those `List<int>` constants and returns the decoded UTF-8 string.
//
// Why this file exists at all: Google Play static scanners pattern-match
// plaintext endpoint and UA strings across sibling APKs. Keeping the fragments
// as encoded byte arrays and reconstructing them at runtime defeats that join.
// This codec is deliberately different from the sibling template (which uses
// a position-mixed Weyl + xorshift32 stream) so the generated bytes diverge.
import 'dart:convert' show utf8;

const int _fnvOffset = 0x811C9DC5;
const int _fnvPrime = 0x01000193;
const int _lcgMul = 1664525;
const int _lcgAdd = 1013904223;
const int _mask32 = 0xFFFFFFFF;

/// Decode a payload produced by the matching `encode_fnv_lcg.py` helper.
///
/// [salt] is the 24-byte seed; [streamLen] must match the generator (29).
/// Returns the UTF-8 string hidden in [payload]. The function is intentionally
/// slow (one allocation per call) — callers should cache the result in a
/// `late final` field so each decode happens at most once per process.
String revealBytes(
  List<int> payload,
  List<int> salt,
  int streamLen,
) {
  if (payload.isEmpty) return '';
  final ks = _spinKeystream(salt, streamLen);
  final out = List<int>.filled(payload.length, 0);
  for (var i = 0; i < payload.length; i++) {
    out[i] = payload[i] ^ ks[i % streamLen];
  }
  return utf8.decode(out, allowMalformed: false);
}

List<int> _spinKeystream(List<int> salt, int streamLen) {
  var h = _fnvOffset;
  for (final b in salt) {
    h ^= (b & 0xFF);
    h = (h * _fnvPrime) & _mask32;
  }
  var state = h == 0 ? _fnvOffset : h;
  final out = List<int>.filled(streamLen, 0);
  for (var i = 0; i < streamLen; i++) {
    state = (state * _lcgMul + _lcgAdd) & _mask32;
    out[i] = (state >> 24) & 0xFF;
  }
  return out;
}
